name: Autobump Versions

on:
  push:
    branches:
      - "master"
      - "main"
      - "versjonering-i-pipeline"

jobs:
  npm-publish:
    name: Check version and bump for new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Should Autobump
        run: npm run bump-version
      - name: Should push result back to git
        run: git push && git push --tags
      - uses: JS-DevTools/npm-publish@v1
        #if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          dry-run: false
